let informations = [ 

{
    id:1,
    img: "images/newAmericanGospel.jpg",
    nameAlbum: "New American Gospel",
    year: 2000,
    musics: [
        "Black Label",
        "A Warning",
        "In the Absence of the Sacred",
        "Letter to the Unborn",
        "The Black Dahlia",
        "Terror and Hubris in the House of Frank Pollard",
        "The Subtle Arts of Murder and Persuasion",
        "Pariah",
        "Confessional",
        "O.D.H.G.A.B.F.E.",
        "Nippon",
        "New Willenium (The Black Dahlia)",
        "Half-Lid (A Warning)",
        "Flux (Pariah)"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=atFwxZXxCs8&t=1s",
}, 
{
    id:2,
    img: "images/asThePalacesBurn.jpg",
    nameAlbum: "As The Palaces Burn",
    year: 2003,
    musics: [
        "Ruin",
        "As The Palaces Burn",
        "Purified",
        "11th Hour",
        "For Your Malice",
        "Boot Scraper",
        "A Devil In God's Country",
        "In Defense Of Our Good Name",
        "Blood Junkie",
        "Vigil"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=whwxIin4uRY",
}, 
{
    id:3,
    img: "images/ashesOfTheWake.jpg",
    nameAlbum: "Ashes Of The Wake",
    year: 2004,
    musics: [
        "Laid to Rest",
        "Hourglass",
        "Now You've Got Something to Die For",
        "The Faded Line",
        "Omerta",
        "Blood Of The Scribe",
        "One Gun",
        "Break You",
        "What I've Become",
        "Ashes of the Wake",
        "Remorse Is for the Dead",
        "Another Nail For Your Coffin",
        "Laid to Rest(Pre-Production Demo)",
        "Ashes of the Wake(Pre-Production Demo)",
        "Remorse Is for the Dead(Pre-Production Demo)"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=sbobZULzNBM&list=PLb_fTldsXf__jdADibeQVjtPk-bADFtef",
}, 
{
    id:4,
    img: "images/sacrament.jpg",
    nameAlbum: "Sacrament",
    year: 2006,
    musics: [
        "Walk with Me In Hell",
        "Again We Rise",
        "Redneck",
        "Pathetic",
        "Foot to the Throat",
        "Descending",
        "Blacken the Cursed Sun",
        "Forgotten(Lost Angels)",
        "Requiem",
        "More Time to Kill",
        "Beating On Deaths Door"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=51pynRFkG80",
}, 
{
    id:5,
    img: "images/wrath.jpg",
    nameAlbum: "Wrath",
    year: 2009,
    musics: [
        "The Passing",
        "In Your Words",
        "Set To Fail",
        "Contractor",
        "Fake Messiah",
        "Grace",
        "Broken Hands",
        "Dead Seeds",
        "Everything To Nothing",
        "Choke Sermon",
        "Reclamation"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=lq9cpVUDxdc",
}, 
{
    id:6,
    img: "images/resolution.jpg",
    nameAlbum: "Resolution",
    year: 2011,
    musics: [
        "Straight For The Sun",
        "Desolation",
        "Ghost Walking",
        "Guilty",
        "The Undertow",
        "The Number Six",
        "Barbarosa",
        "Invictus",
        "Cheated",
        "Insurrection",
        "Terminally Unique",
        "To The End",
        "Visitation",
        "King Me"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=CjpCIwpvlmo",
}, 
{
    id:7,
    img: "images/sturmUndDrang.jpg",
    nameAlbum: "VI: Sturm Und Drang",
    year: 2015,
    musics: [
        "Still Echoes",
        "Erase This",
        "512",
        "Embers (part. Chino Moreno)",
        "Footprints",
        "Overlord",
        "Anthropoid",
        "Engage the Fear Machine",
        "Delusion Pandemic",
        "Torches (part. Greg Puciato)"
    ],
    urlAlbum: "https://www.youtube.com/watch?v=JHW1z19ED1A",
}, 
{
    id:8,
    img: "images/lambOfGod.jpg",
    nameAlbum: "Lamb of God",
    year: 2020,
    musics: [
        "Memento Mori",
        "Checkmate",
        "Gears",
        "Reality Bath",
        "New Colossal Hate",
        "Resurrection Man",
        "Poison Dream (part. Jamey Jasta)",
        "Routes (part. Chuck Billy)",
        "Bloodshot Eyes",
        "On the Hook",
    ],
    urlAlbum: "https://www.youtube.com/watch?v=b-yzjDnjiPA",
}

]


